apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactapp.fullname" . }}
spec:
  selector:
    app: reactapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
