nodeapp:
  image:
    repository: node:18-alpine
    tag: latest
  service:
    port: 8080

reactapp:
  image:
    repository: node:18-alpine
    tag: latest
  service:
    port: 3000

ingress:
  enabled: true
  className: nginx
  host: mydomain.com
  paths:
    - path: /api
      backend: nodeapp
    - path: /ui
      backend: reactapp
