apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodeapp.fullname" . }}
spec:
  selector:
    app: nodeapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
